"""add_initial_domain_models

Revision ID: cf9f780915ed
Revises: 
Create Date: 2026-09-24 09:05:41.818433+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cf9f780915ed'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Unique admin e-mail address used for JWT login'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='bcrypt hash of the admin password'),
    sa.Column('display_name', sa.String(length=120), nullable=True, comment='Human-readable name shown in the dashboard'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft-disable flag; inactive admins cannot authenticate'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_admins_email'),
    comment='Back-office administrator accounts'
    )
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admins_email'), ['email'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='ConversationStatus enum value'),
    sa.Column('visitor_identifier', sa.String(length=255), nullable=True, comment='Optional stable visitor fingerprint or session token'),
    sa.Column('channel', sa.String(length=50), nullable=False, comment='Source channel, e.g. web, widget'),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True, comment='UTC timestamp when the conversation was closed or abandoned'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active', 'closed', 'abandoned')", name='ck_conversations_status'),
    sa.PrimaryKeyConstraint('id'),
    comment='Visitor chat sessions'
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_visitor_identifier'), ['visitor_identifier'], unique=False)

    op.create_table('leads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False, comment='Source Conversation FK; each Conversation yields at most one Lead'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Visitor e-mail collected during conversation'),
    sa.Column('name', sa.String(length=255), nullable=True, comment='Visitor display name'),
    sa.Column('company', sa.String(length=255), nullable=True, comment='Visitor company / organisation'),
    sa.Column('score', sa.Integer(), nullable=False, comment='Current 0-100 algorithmic lead score'),
    sa.Column('qualification_status', sa.String(length=30), nullable=False, comment='LeadQualificationStatus enum value'),
    sa.Column('disqualification_reason', sa.String(length=500), nullable=True, comment='Human-readable reason when status = disqualified'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("qualification_status IN ('new', 'qualifying', 'qualified', 'high_intent', 'not_ready', 'disqualified')", name='ck_leads_qualification_status'),
    sa.CheckConstraint('score >= 0 AND score <= 100', name='ck_leads_score_range'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', name='uq_leads_conversation_id'),
    comment='Visitor leads under BANT qualification'
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_email'), ['email'], unique=False)
        batch_op.create_index('ix_leads_qualification_score', ['qualification_status', 'score'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_qualification_status'), ['qualification_status'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False, comment='Owning Conversation FK'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='MessageRole enum value (visitor | bot | system)'),
    sa.Column('content', sa.Text(), nullable=False, comment='Raw message text'),
    sa.Column('token_count', sa.Integer(), nullable=True, comment='Approximate token count for cost tracking'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('visitor', 'bot', 'system')", name='ck_messages_role'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Individual turns within a Conversation'
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('ix_messages_conversation_created', ['conversation_id', 'created_at'], unique=False)

    op.create_table('bant_states',
    sa.Column('lead_id', sa.String(length=36), nullable=False, comment='FK to leads.id; also the PK of this table (1:1)'),
    sa.Column('budget_status', sa.String(length=20), nullable=False, comment='BANTBudgetStatus enum value'),
    sa.Column('budget_amount', sa.Numeric(precision=15, scale=2), nullable=True, comment='Exact stated budget figure; NULL unless status=specified'),
    sa.Column('budget_currency', sa.String(length=3), nullable=True, comment='ISO-4217 currency code, e.g. USD, INR; NULL unless budget_amount set'),
    sa.Column('budget_evidence', sa.Text(), nullable=True, comment='Quoted or paraphrased evidence from the conversation'),
    sa.Column('authority_level', sa.String(length=20), nullable=False, comment='BANTAuthorityLevel enum value'),
    sa.Column('authority_evidence', sa.Text(), nullable=True, comment='Supporting evidence for authority classification'),
    sa.Column('need_clarity', sa.String(length=20), nullable=False, comment='BANTNeedClarity enum value'),
    sa.Column('need_summary', sa.Text(), nullable=True, comment='Free-text summary of the stated need or problem'),
    sa.Column('need_evidence', sa.Text(), nullable=True, comment='Supporting evidence for need classification'),
    sa.Column('timeline_urgency', sa.String(length=20), nullable=False, comment='BANTTimelineUrgency enum value'),
    sa.Column('timeline_date', sa.DateTime(timezone=True), nullable=True, comment='Explicit target date if the visitor specified one'),
    sa.Column('timeline_evidence', sa.Text(), nullable=True, comment='Supporting evidence for timeline classification'),
    sa.Column('budget_confidence', sa.Float(), nullable=True, comment='Confidence score in [0.0, 1.0] for budget extraction'),
    sa.Column('authority_confidence', sa.Float(), nullable=True, comment='Confidence score in [0.0, 1.0] for authority extraction'),
    sa.Column('need_confidence', sa.Float(), nullable=True, comment='Confidence score in [0.0, 1.0] for need extraction'),
    sa.Column('timeline_confidence', sa.Float(), nullable=True, comment='Confidence score in [0.0, 1.0] for timeline extraction'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('authority_confidence IS NULL OR (authority_confidence >= 0.0 AND authority_confidence <= 1.0)', name='ck_bant_states_authority_confidence'),
    sa.CheckConstraint("authority_level IN ('unknown', 'influencer', 'evaluator', 'decision_maker')", name='ck_bant_states_authority_level'),
    sa.CheckConstraint('budget_amount IS NULL OR budget_amount >= 0', name='ck_bant_states_budget_nonnegative'),
    sa.CheckConstraint('budget_confidence IS NULL OR (budget_confidence >= 0.0 AND budget_confidence <= 1.0)', name='ck_bant_states_budget_confidence'),
    sa.CheckConstraint("budget_status IN ('unknown', 'vague', 'specified', 'none_available')", name='ck_bant_states_budget_status'),
    sa.CheckConstraint('need_confidence IS NULL OR (need_confidence >= 0.0 AND need_confidence <= 1.0)', name='ck_bant_states_need_confidence'),
    sa.CheckConstraint("need_clarity IN ('unknown', 'vague', 'clear', 'specific')", name='ck_bant_states_need_clarity'),
    sa.CheckConstraint('timeline_confidence IS NULL OR (timeline_confidence >= 0.0 AND timeline_confidence <= 1.0)', name='ck_bant_states_timeline_confidence'),
    sa.CheckConstraint("timeline_urgency IN ('unknown', 'long_term', 'short_term', 'immediate')", name='ck_bant_states_timeline_urgency'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lead_id'),
    comment='Live BANT dimension state for a Lead (one row per Lead)'
    )
    op.create_table('lead_score_history',
    sa.Column('id', sa.String(length=36), nullable=False, comment='UUID4 primary key'),
    sa.Column('lead_id', sa.String(length=36), nullable=False, comment='FK to the Lead whose score changed'),
    sa.Column('score', sa.Integer(), nullable=False, comment='Lead score at this point in time (0-100)'),
    sa.Column('message_id', sa.String(length=36), nullable=True, comment='Optional FK to the Message that triggered this score snapshot'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp when this snapshot was recorded'),
    sa.CheckConstraint('score >= 0 AND score <= 100', name='ck_lsh_score_range'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Append-only score snapshot log for Leads'
    )
    with op.batch_alter_table('lead_score_history', schema=None) as batch_op:
        batch_op.create_index('ix_lsh_lead_created', ['lead_id', 'created_at'], unique=False)

    op.create_table('routing_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.String(length=36), nullable=False, comment='FK to the Lead that triggered this action'),
    sa.Column('action_type', sa.String(length=30), nullable=False, comment='RoutingActionType enum value'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='RoutingActionStatus enum value'),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False, comment='Unique key preventing duplicate external actions on retry'),
    sa.Column('payload', sa.Text(), nullable=True, comment='JSON-encoded action payload (recipient, booking URL, etc.)'),
    sa.Column('result_detail', sa.Text(), nullable=True, comment='Integration response or error message for audit trail'),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True, comment='UTC timestamp when the external action was attempted'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("action_type IN ('continue_chat', 'sales_alert', 'calendar_booking')", name='ck_routing_actions_type'),
    sa.CheckConstraint("status IN ('pending', 'success', 'failed')", name='ck_routing_actions_status'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_routing_actions_idempotency_key'),
    comment='Idempotent automated actions triggered by the routing engine'
    )
    with op.batch_alter_table('routing_actions', schema=None) as batch_op:
        batch_op.create_index('ix_routing_actions_lead_id', ['lead_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routing_actions', schema=None) as batch_op:
        batch_op.drop_index('ix_routing_actions_lead_id')

    op.drop_table('routing_actions')
    with op.batch_alter_table('lead_score_history', schema=None) as batch_op:
        batch_op.drop_index('ix_lsh_lead_created')

    op.drop_table('lead_score_history')
    op.drop_table('bant_states')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('ix_messages_conversation_created')

    op.drop_table('messages')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_qualification_status'))
        batch_op.drop_index('ix_leads_qualification_score')
        batch_op.drop_index(batch_op.f('ix_leads_email'))

    op.drop_table('leads')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_visitor_identifier'))

    op.drop_table('conversations')
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admins_email'))

    op.drop_table('admins')
    # ### end Alembic commands ###
